### ISSUE TITLE
react-addons-test-utils is an implicit dependency in order to support react@0.13-14.

### ISSUE THREAD

**Issue by ankushmn** [ankushmn/react-16.7.0-alpha.0#1]
react-addons-test-utils is an implicit dependency in order to support react@0.13-14. Please add the appropriate version to your devDependencies. See https://github.com/airbnb/enzyme#installation
Error: Cannot find module 'react/lib/ReactTestUtils'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\WORK\Ankush\reactjs\nclasser_demo\node_modules\react-addons-test-utils\index.js:1:18)
    at Module._compile (module.js:652:30)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\WORK\Ankush\reactjs\nclasser_demo\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

**Comment by ankushmn** [comment]
package.json
{
  "name": "react-material-admin-template",
  "version": "0.0.1",
  "description": "Admin template using React and Material-UI",
  "engines": {
    "npm": ">=3"
  },
  "scripts": {
    "start": "npm-run-all --parallel test:watch open:src lint:watch",
    "open:src": "babel-node tools/srcServer.js",
    "open:dist": "babel-node tools/distServer.js",
    "lint": "esw webpack.config.* src tools --color",
    "lint:watch": "npm run lint -- --watch",
    "clean-dist": "npm run remove-dist && mkdir dist",
    "remove-dist": "rimraf ./dist",
    "prebuild": "npm run clean-dist && npm run lint && npm run test",
    "build": "babel-node tools/build.js && npm run open:dist",
    "test": "mocha tools/testSetup.js \"src/**/*.spec.js\" --reporter progress",
    "test:cover": "babel-node node_modules/isparta/bin/isparta cover --root src --report html node_modules/mocha/bin/_mocha -- --require ./tools/testSetup.js \"src/**/*.spec.js\" --reporter progress",
    "test:cover:travis": "babel-node node_modules/isparta/bin/isparta cover --root src --report lcovonly _mocha -- --require ./tools/testSetup.js \"src/**/*.spec.js\" && cat ./coverage/lcov.info | node_modules/coveralls/bin/coveralls.js",
    "test:watch": "npm run test -- --watch",
    "open:cover": "npm run test:cover && open coverage/index.html"
  },
  "author": "Rafael Zeffa",
  "license": "MIT",
  "dependencies": {
    "flexboxgrid": "6.3.1",
    "font-awesome": "4.7.0",
    "history": "4.5.1",
    "material-ui": "0.17.0",
    "react": "16.7.0-alpha.0",
    "react-dom": "16.7.0-alpha.0",
    "react-router": "3.0.2",
    "react-tap-event-plugin": "3.0.3",
    "recharts": "0.20.8"
  },
  "devDependencies": {
    "autoprefixer": "6.7.3",
    "babel-cli": "6.26.0",
    "babel-core": "6.23.1",
    "babel-loader": "6.3.2",
    "babel-plugin-react-display-name": "2.0.0",
    "babel-plugin-transform-react-constant-elements": "6.23.0",
    "babel-plugin-transform-react-remove-prop-types": "0.3.2",
    "babel-preset-es2015": "6.22.0",
    "babel-preset-react": "6.23.0",
    "babel-preset-react-hmre": "1.1.1",
    "babel-preset-stage-1": "6.22.0",
    "babel-register": "6.23.0",
    "browser-sync": "2.26.5",
    "chai": "3.5.0",
    "chalk": "1.1.3",
    "connect-history-api-fallback": "1.3.0",
    "coveralls": "2.11.16",
    "cross-env": "3.1.4",
    "css-loader": "0.26.1",
    "enzyme": "2.7.1",
    "enzyme-adapter-react-16": "1.12.1",
    "eslint": "3.15.0",
    "eslint-plugin-import": "2.2.0",
    "eslint-plugin-jsx-a11y": "4.0.0",
    "eslint-plugin-react": "6.10.0",
    "eslint-watch": "3.0.0",
    "extract-text-webpack-plugin": "1.0.1",
    "file-loader": "0.10.0",
    "html-webpack-plugin": "2.22.0",
    "isparta": "4.0.0",
    "mocha": "3.2.0",
    "node-sass": "4.12.0",
    "npm-run-all": "4.0.1",
    "open": "0.0.5",
    "postcss-loader": "1.3.1",
    "prompt": "1.0.0",
    "react-addons-test-utils": "15.2.0",
    "react-test-renderer": "16.8.6",
    "redux-immutable-state-invariant": "1.2.4",
    "replace": "0.3.0",
    "rimraf": "2.5.4",
    "sass-loader": "6.0.1",
    "sinon": "1.17.7",
    "sinon-chai": "2.8.0",
    "style-loader": "0.13.1",
    "url-loader": "0.5.7",
    "webpack": "1.13.1",
    "webpack-dev-middleware": "1.6.1",
    "webpack-hot-middleware": "2.12.2",
    "webpack-md5-hash": "0.0.5"
  },
  "keywords": [
    "react",
    "reactjs",
    "material",
    "material-ui",
    "template",
    "admin"
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/rafaelhz/react-material-admin-template"
  },
  "rules": {
    "import/no-named-as-default": 0
  }
}

**Comment by ankushmn** [comment]
I m stuck here .. can someone help me in this ... thanks in adv?
